### ISSUE TITLE
crash reported on crashlytics

### ISSUE THREAD

**Issue by hisham2007** [PierfrancescoSoffritti/AndroidYouTubePlayer#11]
Many thanks for great work.
crash reported on crashlytics:

`Fatal Exception: java.lang.NullPointerException
       at java.lang.StringToReal.parseFloat(StringToReal.java:285)
       at java.lang.Float.parseFloat(Float.java:300)
       at com.pierfrancescosoffritti.youtubeplayer.YouTubePlayerBridge$9.run(YouTubePlayerBridge.java:169)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by PierfrancescoSoffritti** [comment]
Hi, thank you for reporting the issue. I'll look into it asap :)

**Comment by hisham2007** [comment]
Is there any update ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, sorry for the delay, it's been a busy week. The bug is fixed in version 0.7.6.

**Comment by askarsyzdykov** [comment]
variable 'seconds' is null, you try catching NumberFormatException, 

need add NullPointerException or better 
if (TextUtils.isEmpty(seconds) {
   seconds = "0";
}

**Comment by askarsyzdykov** [comment]
I make the pull request [https://github.com/PierfrancescoSoffritti/AndroidYouTubePlayer/pull/14](url)

**Comment by PierfrancescoSoffritti** [comment]
Thank you, I'll try to review it tomorrow :) I wasn't home for the last few days
